### PR TITLE
feat: change ugettext_lazy to gettext_lazy

### PR DESCRIPTION
**Pull request by Krzysztof-Nerwinski**
Changes depreciated django ugetext_lazy function to gettext_lazy. Works with Django 1.8 to 4.2

### CODE REVIEW

**Comment by Krzysztof-Nerwinski** [comment]
@amateja Hi, should i make a fork on pypi as well or you can find the time to merge this to your git project and publish new version to pypi?

**Comment by amateja** [comment]
Hi @Krzysztof-Nerwinski,

Thank you for your commit.

Main part of it is very accurate so I would like to accept it.

On the other hand I would like to handle versioning myself so please revert this part. Moreover classifiers were not updated for a really long time. Tossing in a few versions here and there doesn't make it right. I'm going to replace setup.py with a new mechanism.

Tests included in .travis.yml also need to get updated.

Therefore I would suggest to keep changes in fields.py and remove all the rest. I'll cover that part myself.

Regards
Andrzej

**Comment by Krzysztof-Nerwinski** [comment]
Thanks for the reply.

I reverted all changes but to ``fields.py``.

Do you need my help with anything that needs to be done or you'll manage?

**Comment by amateja** [comment]
There have been intensive changes in Travis CI platform. Do you have some better options?

**Comment by Krzysztof-Nerwinski** [comment]
I remember reading good opinions about [buildbot](http://buildbot.net/) but I don't have any experience with any of those solutions

**Comment by amateja** [comment]
I've managed to use GitHub Actions. Version 1.1.1 is now released and published to PyPi. Happy using.

Thank you for contributing. Feel free to report any issue.

**Comment by Krzysztof-Nerwinski** [comment]
> I've managed to use GitHub Actions. Version 1.1.1 is now released and published to PyPi. Happy using.

Great, I'll check in your project how you did that.

Anyway, big thank you for finding the time to handle this!

**Pull request merged**
